CREATE DATABASE IF NOT EXISTS `BOOK_MY_COURT`;

USE `BOOK_MY_COURT`;

DROP TABLE IF EXISTS `ROLE`;

--CREATE SEQUENCE ROLE_ID_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE `ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(50),
    PRIMARY KEY `UK_ROLE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--ALTER TABLE ROLES ADD CONSTRAINT PK_ROLES PRIMARY KEY ( ID );


--INSERT INTO ROLES VALUES (1,'ADMIN_USER','This user has admin rights for administrative work');
--INSERT INTO ROLES VALUES (2,'SITE_USER','This user has access to site, after login - normal user');


DROP TABLE IF EXISTS `ROLE`;

--
-- Table structure for table USERS
--

--CREATE SEQUENCE USERS_ID_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE `USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(50),
   `EMAIL` varchar(100),
   `PASSWORD` varchar(100),
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_EMAIL` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--ALTER TABLE USER ADD CONSTRAINT PK_USERS PRIMARY KEY ( ID );
--ALTER TABLE USER ADD CONSTRAINT UK_EMAIL UNIQUE ( EMAIL );


DROP TABLE IF EXISTS `USER_ROLE`;

--CREATE SEQUENCE USER_ROLE_ID_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE `USER_ROLE` (
  `USER_ID` bigint(20) NOT NULL,
  `ROLE_ID` bigint(20) NOT null,

    PRIMARY KEY (`USER_ID`, `ROLE_ID`),

  KEY `FK_USERS` (`USER_ID`),
  CONSTRAINT `FK_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),

   KEY `FK_ROLE` (`ROLE_ID`),
  CONSTRAINT `FK_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--ALTER TABLE USER_ROLES ADD CONSTRAINT PK_USER_ROLE PRIMARY KEY ( USER_ID, ROLE_ID);
--ALTER TABLE USER_ROLES ADD CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER ( ID );
--ALTER TABLE USER_ROLES ADD CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE ( ID );


--
-- Table structure for table COURT
--

DROP TABLE IF EXISTS `COURT`;

-------------------------
-- CREATE SEQUENCE FOR COURT TABLE
------------------------

--CREATE SEQUENCE COURT_ID_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE `COURT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `CITY` varchar(50) NOT NULL,
  `OPENING_TIME` TIMESTAMP NOT NULL,
  `CLOSING_TIME` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--ALTER TABLE COURT ADD CONSTRAINT PK_COURT PRIMARY KEY ( ID );
--ALTER TABLE COURT ADD CONSTRAINT UK_CNAME_AND_CITY UNIQUE ( NAME, CITY);

--
-- Table structure for table SPORT
--

DROP TABLE IF EXISTS `SPORT`;

-------------------------
-- CREATE SEQUENCE FOR SPORT TABLE
------------------------

--CREATE SEQUENCE SPORT_ID_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE `SPORT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `PRICE` bigint(20) NOT NULL,
  `COURT_ID` bigint(20) NOT NULL,
  PRIMARY KEY `UK_SPORT` (`ID`),

  KEY `FK_COURT` (`COURT_ID`),
  CONSTRAINT `FK_COURT` FOREIGN KEY (`COURT_ID`) REFERENCES `COURT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


--ALTER TABLE SPORT ADD CONSTRAINT PK_SPORT PRIMARY KEY ( ID );
--ALTER TABLE SPORT ADD CONSTRAINT FK_COURT FOREIGN KEY (COURT_ID) REFERENCES COURT ( ID );

--
-- Table structure for table BOOKING
--

DROP TABLE IF EXISTS `BOOKING`;

-------------------------
-- CREATE SEQUENCE FOR BOOKING TABLE
------------------------

--CREATE SEQUENCE BOOKING_ID_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE `BOOKING` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SPORT_ID` bigint(20) NOT NULL,
  `START_TIME` TIMESTAMP NOT NULL,
  `END_TIME` TIMESTAMP NOT NULL,
  `AMOUNT` bigint(20) NOT NULL,
   `USER_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),

  KEY `FK_USER` (`USER_ID`),
  CONSTRAINT `FK_USER` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),

   KEY `FK_SPORT` (`SPORT_ID`),
  CONSTRAINT `FK_SPORT` FOREIGN KEY (`SPORT_ID`) REFERENCES `SPORT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


--ALTER TABLE BOOKING ADD CONSTRAINT PK_BOOKING PRIMARY KEY ( ID );
--ALTER TABLE BOOKING ADD CONSTRAINT FK_SPORT FOREIGN KEY (SPORT_ID) REFERENCES SPORT ( ID );
--ALTER TABLE BOOKING ADD CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER ( ID );